# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd3526c4548a227bb27f65d5125e1833d3bb452e474e759cca1f8a7138c84a337eb8d5d59f2ebd4371c866e2f23d920cc97353d3f229b6e43a4c68c297440225

test:
  secret_key_base: 6a0aa27567248dab8bfdb3e30fd4b1b519b614f9ac9ae9001aedb7cb0827a77a9f9dc6de8fe5ecf06f582d53d59df8f1791ee1e032c49297ae01ffc0c833c088

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
